apiVersion: v1
kind: Secret
metadata:
  name: mongo-express-secret
  namespace: mongo-express
type: Opaque
stringData:
  ME_CONFIG_MONGODB_ADMINUSERNAME: YWRtaW4=
  ME_CONFIG_MONGODB_ADMINPASSWORD: YWRtaW4xMjM=

